#!/bin/python3
from tqdm import tqdm
import requests

def generate(country, port):
  py_str = f'zmap -w {country}.zone -p {port}  | ./maoscanv1 -p {port}'
  print(py_str)

def download():
  url = 'https://www.ipdeny.com/ipblocks/data/countries/all-zones.tar.gz'
  response = requests.get(url, stream=True)
  with open("all-zones.tar.gz", "wb") as handle:
    for data in tqdm(response.iter_content()):
        handle.write(data)
  sleep(1)
  os.system('mkdir -p zones')
  os.system('tar -xf all-zones.tar-gz -o zones/')
  os.system('find zone -type f -name "*.zone" -exec sed 's/\.zone//' {} \; >> zone_names')

def main():
  with open("ports.txt","r",encoding="utf-8") as f:
    for ports in f:
      with open('zone_names', 'r', encoding='utf-8') as m:
        for country in m:
          generate(country, ports.strip())

if __name__ == "__main__":
  download()
  main()
